/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as InteriorRouteImport } from './routes/interior'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MenuNameRouteImport } from './routes/menu.$name'

const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorRoute = InteriorRouteImport.update({
  id: '/interior',
  path: '/interior',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuNameRoute = MenuNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => MenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/gallery': typeof GalleryRoute
  '/interior': typeof InteriorRoute
  '/menu': typeof MenuRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/menu/$name': typeof MenuNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/gallery': typeof GalleryRoute
  '/interior': typeof InteriorRoute
  '/menu': typeof MenuRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/menu/$name': typeof MenuNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/gallery': typeof GalleryRoute
  '/interior': typeof InteriorRoute
  '/menu': typeof MenuRouteWithChildren
  '/reservations': typeof ReservationsRoute
  '/menu/$name': typeof MenuNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/branches'
    | '/contact'
    | '/deals'
    | '/gallery'
    | '/interior'
    | '/menu'
    | '/reservations'
    | '/menu/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/branches'
    | '/contact'
    | '/deals'
    | '/gallery'
    | '/interior'
    | '/menu'
    | '/reservations'
    | '/menu/$name'
  id:
    | '__root__'
    | '/'
    | '/branches'
    | '/contact'
    | '/deals'
    | '/gallery'
    | '/interior'
    | '/menu'
    | '/reservations'
    | '/menu/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BranchesRoute: typeof BranchesRoute
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRoute
  GalleryRoute: typeof GalleryRoute
  InteriorRoute: typeof InteriorRoute
  MenuRoute: typeof MenuRouteWithChildren
  ReservationsRoute: typeof ReservationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior': {
      id: '/interior'
      path: '/interior'
      fullPath: '/interior'
      preLoaderRoute: typeof InteriorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$name': {
      id: '/menu/$name'
      path: '/$name'
      fullPath: '/menu/$name'
      preLoaderRoute: typeof MenuNameRouteImport
      parentRoute: typeof MenuRoute
    }
  }
}

interface MenuRouteChildren {
  MenuNameRoute: typeof MenuNameRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuNameRoute: MenuNameRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BranchesRoute: BranchesRoute,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRoute,
  GalleryRoute: GalleryRoute,
  InteriorRoute: InteriorRoute,
  MenuRoute: MenuRouteWithChildren,
  ReservationsRoute: ReservationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
